### ISSUE TITLE
Suggestion: separate py2 and py3 installation

### ISSUE THREAD

**Issue by xareelee** [digital-plumbers-union/rules_pyenv#4]
From this:

```starlark
load("@dpu_rules_pyenv//pyenv:defs.bzl", "pyenv_install")

pyenv_install(
    py2 = "<The version of python2 you want to use for your project>",
    py3 = "<The version of python3 you want to use for your project>",
)
```

to this:

```starlark
load("@dpu_rules_pyenv//pyenv:defs.bzl", "pyenv_install_py2", "pyenv_install_py3")

pyenv_install_py2(
    version = "<The version of python2 you want to use for your project>",
)

pyenv_install_py3(
    version = "<The version of python3 you want to use for your project>",
)
```

I only need Python3 in my project.

**Comment by ddlees** [comment]
@xareelee The `pyenv_install` interface was based on [py_runtime_pair](https://github.com/bazelbuild/bazel/blob/master/tools/python/toolchain.bzl#L42) but something like this should be fairly straightforward. I think we just need to allow `pyenv_install` to allow `None` for the `py{2,3}` params and setup some wrappers for `pyenv_install_py{2,3}`. I'll do my best to get to it soon but PRs are welcome if you find yourself getting impatient. 😉

**Comment by haberman** [comment]
I'm wanting this also. I have a project that I want to support Python 3 only.
